### ISSUE TITLE
BirdDog PTZ Cameras

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-birddog-visca#1]
Device: BirdDog PTZ camera line (P100, P200, etc)
Goal: To be able to control camera settings, especially recalling presets, and other image control tasks.
Links: BirdDog's API. The camera portion starts with "Camera Products" on page 4.
[https://www.bird-dog.tv/extra/BirdDog_RESTful_API_1.0.pdf](https://www.bird-dog.tv/extra/BirdDog_RESTful_API_1.0.pdf)

I'm happy to help test and add to this, starting from scratch is just slightly out of my scope.

**Comment by BenniMTools** [comment]
Created a Birddog Module
