### ISSUE TITLE
only position presets

### ISSUE THREAD

**Issue by dominik34** [bitfocus/companion-module-birddog-visca#10]
Hey, it would be nice to have "only position presets". - Presets with only the ptz/zoom position stored and without white balance, exposure,....settings.

I am mostly using manual settings for exposure, wb,...and my cams are fix mounted. So the positions are always the same but the light is changing. So I want to do the picture settings separately from the positions.

I hope you understand what I mean and there's an option to do this. I haven't found a visca command to do this yet.
Anyway. Thanks a lot for this companion module!

**Comment by BenniMTools** [comment]
Hello Dominik,
you have to change the Preset Memory in the OSD Settings of the Camera.

OSD -> System -> Preset Memory.
On all settings are stored, Off only Pan/Tilt Zoom is Stored.

P200 Manual Page 19  ;-)

Best,
Benni
