### ISSUE TITLE
Inclusion of firmware version in release notes

### ISSUE THREAD

**Issue by pjbisset** [bitfocus/companion-module-birddog-visca#11]
I have two P100s and recently upgraded one to v21.01.3766. The other is running v3.2.5. Currently running Companion v2.1.1. Prior to the upgrade I was using the Sony Visca module to control the cameras (save/recall presets, zoom) - the Birddog Visca module did not work. After the firmware upgrade the Sony Visca module no longer worked, but the Birddog module did. I have had to alter all the controls to work with the new module - not a big deal, but was a surprise.

I think it would be helpful to include the Birddog firmware version used to develop/test the Birddog module in future releases, just so people know what is required in order to use the module, and perhaps be prepared for the rework that may be necessary due to a firmware update.

**Comment by BenniMTools** [comment]
Hi Peter,

thanks for the Information.
The Module is testet with version 3.3 and above.
I will update the Readme with this information.
