### ISSUE TITLE
Update Module in Companion

### ISSUE THREAD

**Issue by joakyhsf69** [bitfocus/companion-module-birddog-visca#15]
Hello, I see that in version 2.1.3 of the companion there is still version 1.0.0 of this module. I have some problems, such as the preset number or the preset call speed that I expected to be solved, but I can't find how to update to version 1.0.3 that is published here. Could you help me? Thanks

**Comment by bryce-seifert** [comment]
There's no current way to update a specific module within Companion. Instead, you need to update companion itself, which you can do by downloading one of the [release candidate or beta builds here.](https://bitfocus.io/companion/download/builds/)
